#!/bin/bash

NETNS=torrent
IP=/usr/bin/ip
VETH0_IP=10.200.1.1
VETH1_IP=10.200.1.2

#Here, we assume you use nordVPN and your openVPN config files are located on a mounted
#pendrive at /mnt/data/nordVPN
VPN_ROOT=~/nordVPN/openvpn_configs/
#this variable will be used as a grep argument to filter out the vpn servers that are in the same country
VPN_COUNTRY=uk




check_exit ()
{
  exit_code=$1
  error_msg=$2

  if [ $exit_code -ne 0 ]
  then
    echo $error_msg
  else
    echo  "                             [SUCCESS]"
  fi
}

